[terminal.shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux attach ||  tmux new"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 4
padding.y = 4
dynamic_padding = true
dynamic_title = true
decorations_theme_variant = "Dark"

[font]
size = 10

[font.normal]
family = "JetBrainsMono Nerd Font"

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.bold]
family = "JetBrainsMono Nerd Font"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"

[selection]
save_to_clipboard = true
