[terminal.shell]
program = "/bin/zsh"
args = ["-l", "-c", 'tmux', '-a']

[env]
TERM = "xterm-256color"

[window]
padding.x = 4
padding.y = 4
dynamic_padding = true
dynamic_title = true
decorations_theme_variant = "Dark"

[font]
size = 10.0

normal.family = "JetBrainsMonoNL Nerd Font"
bold.family = "JetBrainsMonoNL Nerd Font"
italic.family = "JetBrainsMonoNL Nerd Font"
bold_italic.family = "JetBrainsMonoNL Nerd Font"

[selection]
save_to_clipboard = true
